/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collection Pattern CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.uma.usex.usex.CollectionPatternCS#getOwnedType <em>Owned Type</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.CollectionPatternCS#getOwnedParts <em>Owned Parts</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.CollectionPatternCS#getRestVariableName <em>Rest Variable Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.uma.usex.usex.UsexPackage#getCollectionPatternCS()
 * @model
 * @generated
 */
public interface CollectionPatternCS extends TypedRefCS
{
  /**
   * Returns the value of the '<em><b>Owned Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Type</em>' containment reference.
   * @see #setOwnedType(CollectionTypeCS)
   * @see org.xtext.uma.usex.usex.UsexPackage#getCollectionPatternCS_OwnedType()
   * @model containment="true"
   * @generated
   */
  CollectionTypeCS getOwnedType();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.CollectionPatternCS#getOwnedType <em>Owned Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Type</em>' containment reference.
   * @see #getOwnedType()
   * @generated
   */
  void setOwnedType(CollectionTypeCS value);

  /**
   * Returns the value of the '<em><b>Owned Parts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.uma.usex.usex.PatternExpCS}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Parts</em>' containment reference list.
   * @see org.xtext.uma.usex.usex.UsexPackage#getCollectionPatternCS_OwnedParts()
   * @model containment="true"
   * @generated
   */
  EList<PatternExpCS> getOwnedParts();

  /**
   * Returns the value of the '<em><b>Rest Variable Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rest Variable Name</em>' attribute.
   * @see #setRestVariableName(String)
   * @see org.xtext.uma.usex.usex.UsexPackage#getCollectionPatternCS_RestVariableName()
   * @model
   * @generated
   */
  String getRestVariableName();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.CollectionPatternCS#getRestVariableName <em>Rest Variable Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rest Variable Name</em>' attribute.
   * @see #getRestVariableName()
   * @generated
   */
  void setRestVariableName(String value);

} // CollectionPatternCS
