/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.uma.usex.usex.UsexPackage#getComposition()
 * @model
 * @generated
 */
public interface Composition extends Relation
{
} // Composition
