/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.uma.usex.usex.Constraint#getConditionBody <em>Condition Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.uma.usex.usex.UsexPackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Body</em>' containment reference.
   * @see #setConditionBody(ConditionBody)
   * @see org.xtext.uma.usex.usex.UsexPackage#getConstraint_ConditionBody()
   * @model containment="true"
   * @generated
   */
  ConditionBody getConditionBody();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.Constraint#getConditionBody <em>Condition Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition Body</em>' containment reference.
   * @see #getConditionBody()
   * @generated
   */
  void setConditionBody(ConditionBody value);

} // Constraint
