/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lambda Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.uma.usex.usex.LambdaLiteralExpCS#getOwnedExpressionCS <em>Owned Expression CS</em>}</li>
 * </ul>
 *
 * @see org.xtext.uma.usex.usex.UsexPackage#getLambdaLiteralExpCS()
 * @model
 * @generated
 */
public interface LambdaLiteralExpCS extends ExpCS
{
  /**
   * Returns the value of the '<em><b>Owned Expression CS</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Expression CS</em>' containment reference.
   * @see #setOwnedExpressionCS(ExpCS)
   * @see org.xtext.uma.usex.usex.UsexPackage#getLambdaLiteralExpCS_OwnedExpressionCS()
   * @model containment="true"
   * @generated
   */
  ExpCS getOwnedExpressionCS();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.LambdaLiteralExpCS#getOwnedExpressionCS <em>Owned Expression CS</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Expression CS</em>' containment reference.
   * @see #getOwnedExpressionCS()
   * @generated
   */
  void setOwnedExpressionCS(ExpCS value);

} // LambdaLiteralExpCS
