/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Navigating Arg CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.uma.usex.usex.NavigatingArgCS#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.NavigatingArgCS#getOwnedNameExpression <em>Owned Name Expression</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.NavigatingArgCS#getSymbolT <em>Symbol T</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.NavigatingArgCS#getOwnedType <em>Owned Type</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.NavigatingArgCS#getSymbolIE <em>Symbol IE</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.NavigatingArgCS#getOwnedInitExpression <em>Owned Init Expression</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.NavigatingArgCS#getSymbolCI <em>Symbol CI</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.NavigatingArgCS#getOwnedCoIterator <em>Owned Co Iterator</em>}</li>
 * </ul>
 *
 * @see org.xtext.uma.usex.usex.UsexPackage#getNavigatingArgCS()
 * @model
 * @generated
 */
public interface NavigatingArgCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' attribute.
   * @see #setPrefix(String)
   * @see org.xtext.uma.usex.usex.UsexPackage#getNavigatingArgCS_Prefix()
   * @model
   * @generated
   */
  String getPrefix();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.NavigatingArgCS#getPrefix <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' attribute.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(String value);

  /**
   * Returns the value of the '<em><b>Owned Name Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Name Expression</em>' containment reference.
   * @see #setOwnedNameExpression(ExpCS)
   * @see org.xtext.uma.usex.usex.UsexPackage#getNavigatingArgCS_OwnedNameExpression()
   * @model containment="true"
   * @generated
   */
  ExpCS getOwnedNameExpression();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.NavigatingArgCS#getOwnedNameExpression <em>Owned Name Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Name Expression</em>' containment reference.
   * @see #getOwnedNameExpression()
   * @generated
   */
  void setOwnedNameExpression(ExpCS value);

  /**
   * Returns the value of the '<em><b>Symbol T</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symbol T</em>' attribute.
   * @see #setSymbolT(String)
   * @see org.xtext.uma.usex.usex.UsexPackage#getNavigatingArgCS_SymbolT()
   * @model
   * @generated
   */
  String getSymbolT();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.NavigatingArgCS#getSymbolT <em>Symbol T</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symbol T</em>' attribute.
   * @see #getSymbolT()
   * @generated
   */
  void setSymbolT(String value);

  /**
   * Returns the value of the '<em><b>Owned Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Type</em>' containment reference.
   * @see #setOwnedType(TypedRefCS)
   * @see org.xtext.uma.usex.usex.UsexPackage#getNavigatingArgCS_OwnedType()
   * @model containment="true"
   * @generated
   */
  TypedRefCS getOwnedType();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.NavigatingArgCS#getOwnedType <em>Owned Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Type</em>' containment reference.
   * @see #getOwnedType()
   * @generated
   */
  void setOwnedType(TypedRefCS value);

  /**
   * Returns the value of the '<em><b>Symbol IE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symbol IE</em>' attribute.
   * @see #setSymbolIE(String)
   * @see org.xtext.uma.usex.usex.UsexPackage#getNavigatingArgCS_SymbolIE()
   * @model
   * @generated
   */
  String getSymbolIE();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.NavigatingArgCS#getSymbolIE <em>Symbol IE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symbol IE</em>' attribute.
   * @see #getSymbolIE()
   * @generated
   */
  void setSymbolIE(String value);

  /**
   * Returns the value of the '<em><b>Owned Init Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Init Expression</em>' containment reference.
   * @see #setOwnedInitExpression(ExpCS)
   * @see org.xtext.uma.usex.usex.UsexPackage#getNavigatingArgCS_OwnedInitExpression()
   * @model containment="true"
   * @generated
   */
  ExpCS getOwnedInitExpression();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.NavigatingArgCS#getOwnedInitExpression <em>Owned Init Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Init Expression</em>' containment reference.
   * @see #getOwnedInitExpression()
   * @generated
   */
  void setOwnedInitExpression(ExpCS value);

  /**
   * Returns the value of the '<em><b>Symbol CI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symbol CI</em>' attribute.
   * @see #setSymbolCI(String)
   * @see org.xtext.uma.usex.usex.UsexPackage#getNavigatingArgCS_SymbolCI()
   * @model
   * @generated
   */
  String getSymbolCI();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.NavigatingArgCS#getSymbolCI <em>Symbol CI</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symbol CI</em>' attribute.
   * @see #getSymbolCI()
   * @generated
   */
  void setSymbolCI(String value);

  /**
   * Returns the value of the '<em><b>Owned Co Iterator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Co Iterator</em>' containment reference.
   * @see #setOwnedCoIterator(VariableCS)
   * @see org.xtext.uma.usex.usex.UsexPackage#getNavigatingArgCS_OwnedCoIterator()
   * @model containment="true"
   * @generated
   */
  VariableCS getOwnedCoIterator();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.NavigatingArgCS#getOwnedCoIterator <em>Owned Co Iterator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Co Iterator</em>' containment reference.
   * @see #getOwnedCoIterator()
   * @generated
   */
  void setOwnedCoIterator(VariableCS value);

} // NavigatingArgCS
