/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nested Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.uma.usex.usex.NestedExpCS#getOwnedExpression <em>Owned Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.uma.usex.usex.UsexPackage#getNestedExpCS()
 * @model
 * @generated
 */
public interface NestedExpCS extends ExpCS
{
  /**
   * Returns the value of the '<em><b>Owned Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Expression</em>' containment reference.
   * @see #setOwnedExpression(ExpCS)
   * @see org.xtext.uma.usex.usex.UsexPackage#getNestedExpCS_OwnedExpression()
   * @model containment="true"
   * @generated
   */
  ExpCS getOwnedExpression();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.NestedExpCS#getOwnedExpression <em>Owned Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Expression</em>' containment reference.
   * @see #getOwnedExpression()
   * @generated
   */
  void setOwnedExpression(ExpCS value);

} // NestedExpCS
