/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.uma.usex.usex.RelationBody#getOriginClass <em>Origin Class</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.RelationBody#getDestinyClass <em>Destiny Class</em>}</li>
 * </ul>
 *
 * @see org.xtext.uma.usex.usex.UsexPackage#getRelationBody()
 * @model
 * @generated
 */
public interface RelationBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Origin Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Origin Class</em>' containment reference.
   * @see #setOriginClass(RelationMember)
   * @see org.xtext.uma.usex.usex.UsexPackage#getRelationBody_OriginClass()
   * @model containment="true"
   * @generated
   */
  RelationMember getOriginClass();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.RelationBody#getOriginClass <em>Origin Class</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Origin Class</em>' containment reference.
   * @see #getOriginClass()
   * @generated
   */
  void setOriginClass(RelationMember value);

  /**
   * Returns the value of the '<em><b>Destiny Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destiny Class</em>' containment reference.
   * @see #setDestinyClass(RelationMember)
   * @see org.xtext.uma.usex.usex.UsexPackage#getRelationBody_DestinyClass()
   * @model containment="true"
   * @generated
   */
  RelationMember getDestinyClass();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.RelationBody#getDestinyClass <em>Destiny Class</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destiny Class</em>' containment reference.
   * @see #getDestinyClass()
   * @generated
   */
  void setDestinyClass(RelationMember value);

} // RelationBody
