/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Round Bracketed Clause CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.uma.usex.usex.RoundBracketedClauseCS#getOwnedArguments <em>Owned Arguments</em>}</li>
 * </ul>
 *
 * @see org.xtext.uma.usex.usex.UsexPackage#getRoundBracketedClauseCS()
 * @model
 * @generated
 */
public interface RoundBracketedClauseCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Owned Arguments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.uma.usex.usex.NavigatingArgCS}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Arguments</em>' containment reference list.
   * @see org.xtext.uma.usex.usex.UsexPackage#getRoundBracketedClauseCS_OwnedArguments()
   * @model containment="true"
   * @generated
   */
  EList<NavigatingArgCS> getOwnedArguments();

} // RoundBracketedClauseCS
