/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tuple Literal Part CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.uma.usex.usex.TupleLiteralPartCS#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.TupleLiteralPartCS#getOwnedType <em>Owned Type</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.TupleLiteralPartCS#getOwnedInitExpression <em>Owned Init Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.uma.usex.usex.UsexPackage#getTupleLiteralPartCS()
 * @model
 * @generated
 */
public interface TupleLiteralPartCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.uma.usex.usex.UsexPackage#getTupleLiteralPartCS_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.TupleLiteralPartCS#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Owned Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Type</em>' containment reference.
   * @see #setOwnedType(TypedRefCS)
   * @see org.xtext.uma.usex.usex.UsexPackage#getTupleLiteralPartCS_OwnedType()
   * @model containment="true"
   * @generated
   */
  TypedRefCS getOwnedType();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.TupleLiteralPartCS#getOwnedType <em>Owned Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Type</em>' containment reference.
   * @see #getOwnedType()
   * @generated
   */
  void setOwnedType(TypedRefCS value);

  /**
   * Returns the value of the '<em><b>Owned Init Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Init Expression</em>' containment reference.
   * @see #setOwnedInitExpression(ExpCS)
   * @see org.xtext.uma.usex.usex.UsexPackage#getTupleLiteralPartCS_OwnedInitExpression()
   * @model containment="true"
   * @generated
   */
  ExpCS getOwnedInitExpression();

  /**
   * Sets the value of the '{@link org.xtext.uma.usex.usex.TupleLiteralPartCS#getOwnedInitExpression <em>Owned Init Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Init Expression</em>' containment reference.
   * @see #getOwnedInitExpression()
   * @generated
   */
  void setOwnedInitExpression(ExpCS value);

} // TupleLiteralPartCS
