/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.uma.usex.usex.UsexFactory
 * @model kind="package"
 * @generated
 */
public interface UsexPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "usex";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/uma/usex/Usex";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "usex";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UsexPackage eINSTANCE = org.xtext.uma.usex.usex.impl.UsexPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.ModelImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.AbstractElementImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.UseClassImpl <em>Use Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.UseClassImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getUseClass()
   * @generated
   */
  int USE_CLASS = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CLASS__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CLASS__ATTRIBUTES = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CLASS__OPERATIONS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CLASS__CONSTRAINTS = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Use Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CLASS_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.AttributeImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 1;

  /**
   * The feature id for the '<em><b>Initialization</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__INITIALIZATION = 2;

  /**
   * The feature id for the '<em><b>Derived From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__DERIVED_FROM = 3;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.AttributeTypeImpl <em>Attribute Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.AttributeTypeImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAttributeType()
   * @generated
   */
  int ATTRIBUTE_TYPE = 4;

  /**
   * The number of structural features of the '<em>Attribute Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.PrimitiveTypeImpl <em>Primitive Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.PrimitiveTypeImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getPrimitiveType()
   * @generated
   */
  int PRIMITIVE_TYPE = 5;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE__TYPE = ATTRIBUTE_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Primitive Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE_FEATURE_COUNT = ATTRIBUTE_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.ClassTypeImpl <em>Class Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.ClassTypeImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getClassType()
   * @generated
   */
  int CLASS_TYPE = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_TYPE__TYPE = ATTRIBUTE_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Class Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_TYPE_FEATURE_COUNT = ATTRIBUTE_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.AttributeInitializationImpl <em>Attribute Initialization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.AttributeInitializationImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAttributeInitialization()
   * @generated
   */
  int ATTRIBUTE_INITIALIZATION = 7;

  /**
   * The number of structural features of the '<em>Attribute Initialization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_INITIALIZATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.DoubleInitializationImpl <em>Double Initialization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.DoubleInitializationImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getDoubleInitialization()
   * @generated
   */
  int DOUBLE_INITIALIZATION = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_INITIALIZATION__VALUE = ATTRIBUTE_INITIALIZATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Double Initialization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_INITIALIZATION_FEATURE_COUNT = ATTRIBUTE_INITIALIZATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.BooleanInitializationImpl <em>Boolean Initialization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.BooleanInitializationImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getBooleanInitialization()
   * @generated
   */
  int BOOLEAN_INITIALIZATION = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_INITIALIZATION__VALUE = ATTRIBUTE_INITIALIZATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Initialization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_INITIALIZATION_FEATURE_COUNT = ATTRIBUTE_INITIALIZATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.IntegerInitializationImpl <em>Integer Initialization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.IntegerInitializationImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getIntegerInitialization()
   * @generated
   */
  int INTEGER_INITIALIZATION = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_INITIALIZATION__VALUE = ATTRIBUTE_INITIALIZATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Integer Initialization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_INITIALIZATION_FEATURE_COUNT = ATTRIBUTE_INITIALIZATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.StringInitializationImpl <em>String Initialization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.StringInitializationImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getStringInitialization()
   * @generated
   */
  int STRING_INITIALIZATION = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_INITIALIZATION__VALUE = ATTRIBUTE_INITIALIZATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Initialization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_INITIALIZATION_FEATURE_COUNT = ATTRIBUTE_INITIALIZATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.OperationImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Input Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__INPUT_PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Return Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__RETURN_PARAMETER = 2;

  /**
   * The feature id for the '<em><b>Operation Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__OPERATION_BODY = 3;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.MethodImpl <em>Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.MethodImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getMethod()
   * @generated
   */
  int METHOD = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__NAME = OPERATION__NAME;

  /**
   * The feature id for the '<em><b>Input Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__INPUT_PARAMETERS = OPERATION__INPUT_PARAMETERS;

  /**
   * The feature id for the '<em><b>Return Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__RETURN_PARAMETER = OPERATION__RETURN_PARAMETER;

  /**
   * The feature id for the '<em><b>Operation Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__OPERATION_BODY = OPERATION__OPERATION_BODY;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__CONDITIONS = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.QueryImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__NAME = OPERATION__NAME;

  /**
   * The feature id for the '<em><b>Input Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__INPUT_PARAMETERS = OPERATION__INPUT_PARAMETERS;

  /**
   * The feature id for the '<em><b>Return Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__RETURN_PARAMETER = OPERATION__RETURN_PARAMETER;

  /**
   * The feature id for the '<em><b>Operation Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__OPERATION_BODY = OPERATION__OPERATION_BODY;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.ParameterImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__TYPE = 1;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.ConditionImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 16;

  /**
   * The feature id for the '<em><b>Condition Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONDITION_BODY = 0;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.PreconditionImpl <em>Precondition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.PreconditionImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getPrecondition()
   * @generated
   */
  int PRECONDITION = 17;

  /**
   * The feature id for the '<em><b>Condition Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRECONDITION__CONDITION_BODY = CONDITION__CONDITION_BODY;

  /**
   * The number of structural features of the '<em>Precondition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRECONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.PostconditionImpl <em>Postcondition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.PostconditionImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getPostcondition()
   * @generated
   */
  int POSTCONDITION = 18;

  /**
   * The feature id for the '<em><b>Condition Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTCONDITION__CONDITION_BODY = CONDITION__CONDITION_BODY;

  /**
   * The number of structural features of the '<em>Postcondition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTCONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.ConditionBodyImpl <em>Condition Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.ConditionBodyImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getConditionBody()
   * @generated
   */
  int CONDITION_BODY = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_BODY__NAME = 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_BODY__CONDITION = 1;

  /**
   * The number of structural features of the '<em>Condition Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.ConstraintImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 20;

  /**
   * The feature id for the '<em><b>Condition Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__CONDITION_BODY = 0;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.RelationImpl <em>Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.RelationImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getRelation()
   * @generated
   */
  int RELATION = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Relation Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__RELATION_BODY = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.AssociationImpl <em>Association</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.AssociationImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAssociation()
   * @generated
   */
  int ASSOCIATION = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__NAME = RELATION__NAME;

  /**
   * The feature id for the '<em><b>Relation Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__RELATION_BODY = RELATION__RELATION_BODY;

  /**
   * The number of structural features of the '<em>Association</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_FEATURE_COUNT = RELATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.CompositionImpl <em>Composition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.CompositionImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getComposition()
   * @generated
   */
  int COMPOSITION = 23;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION__NAME = RELATION__NAME;

  /**
   * The feature id for the '<em><b>Relation Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION__RELATION_BODY = RELATION__RELATION_BODY;

  /**
   * The number of structural features of the '<em>Composition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION_FEATURE_COUNT = RELATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.RelationBodyImpl <em>Relation Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.RelationBodyImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getRelationBody()
   * @generated
   */
  int RELATION_BODY = 24;

  /**
   * The feature id for the '<em><b>Origin Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_BODY__ORIGIN_CLASS = 0;

  /**
   * The feature id for the '<em><b>Destiny Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_BODY__DESTINY_CLASS = 1;

  /**
   * The number of structural features of the '<em>Relation Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.RelationMemberImpl <em>Relation Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.RelationMemberImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getRelationMember()
   * @generated
   */
  int RELATION_MEMBER = 25;

  /**
   * The feature id for the '<em><b>Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_MEMBER__CLASS = 0;

  /**
   * The feature id for the '<em><b>Cardinality</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_MEMBER__CARDINALITY = 1;

  /**
   * The feature id for the '<em><b>Role Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_MEMBER__ROLE_NAME = 2;

  /**
   * The number of structural features of the '<em>Relation Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_MEMBER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.CardinalityTypeImpl <em>Cardinality Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.CardinalityTypeImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getCardinalityType()
   * @generated
   */
  int CARDINALITY_TYPE = 26;

  /**
   * The number of structural features of the '<em>Cardinality Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARDINALITY_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.SimpleCardinalityImpl <em>Simple Cardinality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.SimpleCardinalityImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getSimpleCardinality()
   * @generated
   */
  int SIMPLE_CARDINALITY = 27;

  /**
   * The feature id for the '<em><b>Cardinality</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_CARDINALITY__CARDINALITY = CARDINALITY_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Simple Cardinality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_CARDINALITY_FEATURE_COUNT = CARDINALITY_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.DoubleCardinalityImpl <em>Double Cardinality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.DoubleCardinalityImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getDoubleCardinality()
   * @generated
   */
  int DOUBLE_CARDINALITY = 28;

  /**
   * The feature id for the '<em><b>Origin Cardinality</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_CARDINALITY__ORIGIN_CARDINALITY = CARDINALITY_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Destiny Cardinality</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_CARDINALITY__DESTINY_CARDINALITY = CARDINALITY_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Double Cardinality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_CARDINALITY_FEATURE_COUNT = CARDINALITY_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.CardinalityValueImpl <em>Cardinality Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.CardinalityValueImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getCardinalityValue()
   * @generated
   */
  int CARDINALITY_VALUE = 29;

  /**
   * The number of structural features of the '<em>Cardinality Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARDINALITY_VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.IntCardinalityImpl <em>Int Cardinality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.IntCardinalityImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getIntCardinality()
   * @generated
   */
  int INT_CARDINALITY = 30;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_CARDINALITY__VALUE = CARDINALITY_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Cardinality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_CARDINALITY_FEATURE_COUNT = CARDINALITY_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.uma.usex.usex.impl.AsteriskCardinalityImpl <em>Asterisk Cardinality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.uma.usex.usex.impl.AsteriskCardinalityImpl
   * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAsteriskCardinality()
   * @generated
   */
  int ASTERISK_CARDINALITY = 31;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASTERISK_CARDINALITY__VALUE = CARDINALITY_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Asterisk Cardinality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASTERISK_CARDINALITY_FEATURE_COUNT = CARDINALITY_VALUE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.uma.usex.usex.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.uma.usex.usex.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.uma.usex.usex.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.uma.usex.usex.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.xtext.uma.usex.usex.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.AbstractElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.uma.usex.usex.AbstractElement#getName()
   * @see #getAbstractElement()
   * @generated
   */
  EAttribute getAbstractElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.UseClass <em>Use Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Class</em>'.
   * @see org.xtext.uma.usex.usex.UseClass
   * @generated
   */
  EClass getUseClass();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.uma.usex.usex.UseClass#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.xtext.uma.usex.usex.UseClass#getAttributes()
   * @see #getUseClass()
   * @generated
   */
  EReference getUseClass_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.uma.usex.usex.UseClass#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.uma.usex.usex.UseClass#getOperations()
   * @see #getUseClass()
   * @generated
   */
  EReference getUseClass_Operations();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.uma.usex.usex.UseClass#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraints</em>'.
   * @see org.xtext.uma.usex.usex.UseClass#getConstraints()
   * @see #getUseClass()
   * @generated
   */
  EReference getUseClass_Constraints();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see org.xtext.uma.usex.usex.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.uma.usex.usex.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.uma.usex.usex.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.Attribute#getInitialization <em>Initialization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Initialization</em>'.
   * @see org.xtext.uma.usex.usex.Attribute#getInitialization()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Initialization();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.Attribute#getDerivedFrom <em>Derived From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Derived From</em>'.
   * @see org.xtext.uma.usex.usex.Attribute#getDerivedFrom()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_DerivedFrom();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.AttributeType <em>Attribute Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Type</em>'.
   * @see org.xtext.uma.usex.usex.AttributeType
   * @generated
   */
  EClass getAttributeType();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.PrimitiveType <em>Primitive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primitive Type</em>'.
   * @see org.xtext.uma.usex.usex.PrimitiveType
   * @generated
   */
  EClass getPrimitiveType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.PrimitiveType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.uma.usex.usex.PrimitiveType#getType()
   * @see #getPrimitiveType()
   * @generated
   */
  EAttribute getPrimitiveType_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.ClassType <em>Class Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Type</em>'.
   * @see org.xtext.uma.usex.usex.ClassType
   * @generated
   */
  EClass getClassType();

  /**
   * Returns the meta object for the reference '{@link org.xtext.uma.usex.usex.ClassType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.uma.usex.usex.ClassType#getType()
   * @see #getClassType()
   * @generated
   */
  EReference getClassType_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.AttributeInitialization <em>Attribute Initialization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Initialization</em>'.
   * @see org.xtext.uma.usex.usex.AttributeInitialization
   * @generated
   */
  EClass getAttributeInitialization();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.DoubleInitialization <em>Double Initialization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Double Initialization</em>'.
   * @see org.xtext.uma.usex.usex.DoubleInitialization
   * @generated
   */
  EClass getDoubleInitialization();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.DoubleInitialization#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.uma.usex.usex.DoubleInitialization#getValue()
   * @see #getDoubleInitialization()
   * @generated
   */
  EAttribute getDoubleInitialization_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.BooleanInitialization <em>Boolean Initialization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Initialization</em>'.
   * @see org.xtext.uma.usex.usex.BooleanInitialization
   * @generated
   */
  EClass getBooleanInitialization();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.BooleanInitialization#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.uma.usex.usex.BooleanInitialization#getValue()
   * @see #getBooleanInitialization()
   * @generated
   */
  EAttribute getBooleanInitialization_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.IntegerInitialization <em>Integer Initialization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer Initialization</em>'.
   * @see org.xtext.uma.usex.usex.IntegerInitialization
   * @generated
   */
  EClass getIntegerInitialization();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.IntegerInitialization#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.uma.usex.usex.IntegerInitialization#getValue()
   * @see #getIntegerInitialization()
   * @generated
   */
  EAttribute getIntegerInitialization_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.StringInitialization <em>String Initialization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Initialization</em>'.
   * @see org.xtext.uma.usex.usex.StringInitialization
   * @generated
   */
  EClass getStringInitialization();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.StringInitialization#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.uma.usex.usex.StringInitialization#getValue()
   * @see #getStringInitialization()
   * @generated
   */
  EAttribute getStringInitialization_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.uma.usex.usex.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.Operation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.uma.usex.usex.Operation#getName()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.uma.usex.usex.Operation#getInputParameters <em>Input Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Input Parameters</em>'.
   * @see org.xtext.uma.usex.usex.Operation#getInputParameters()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_InputParameters();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.Operation#getReturnParameter <em>Return Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return Parameter</em>'.
   * @see org.xtext.uma.usex.usex.Operation#getReturnParameter()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_ReturnParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.Operation#getOperationBody <em>Operation Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation Body</em>'.
   * @see org.xtext.uma.usex.usex.Operation#getOperationBody()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_OperationBody();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Method <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method</em>'.
   * @see org.xtext.uma.usex.usex.Method
   * @generated
   */
  EClass getMethod();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.uma.usex.usex.Method#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see org.xtext.uma.usex.usex.Method#getConditions()
   * @see #getMethod()
   * @generated
   */
  EReference getMethod_Conditions();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see org.xtext.uma.usex.usex.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.xtext.uma.usex.usex.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.uma.usex.usex.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.Parameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.uma.usex.usex.Parameter#getType()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.xtext.uma.usex.usex.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.Condition#getConditionBody <em>Condition Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Body</em>'.
   * @see org.xtext.uma.usex.usex.Condition#getConditionBody()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_ConditionBody();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Precondition <em>Precondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Precondition</em>'.
   * @see org.xtext.uma.usex.usex.Precondition
   * @generated
   */
  EClass getPrecondition();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Postcondition <em>Postcondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Postcondition</em>'.
   * @see org.xtext.uma.usex.usex.Postcondition
   * @generated
   */
  EClass getPostcondition();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.ConditionBody <em>Condition Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition Body</em>'.
   * @see org.xtext.uma.usex.usex.ConditionBody
   * @generated
   */
  EClass getConditionBody();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.ConditionBody#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.uma.usex.usex.ConditionBody#getName()
   * @see #getConditionBody()
   * @generated
   */
  EAttribute getConditionBody_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.ConditionBody#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.xtext.uma.usex.usex.ConditionBody#getCondition()
   * @see #getConditionBody()
   * @generated
   */
  EAttribute getConditionBody_Condition();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see org.xtext.uma.usex.usex.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.Constraint#getConditionBody <em>Condition Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Body</em>'.
   * @see org.xtext.uma.usex.usex.Constraint#getConditionBody()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_ConditionBody();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Relation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation</em>'.
   * @see org.xtext.uma.usex.usex.Relation
   * @generated
   */
  EClass getRelation();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.Relation#getRelationBody <em>Relation Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Relation Body</em>'.
   * @see org.xtext.uma.usex.usex.Relation#getRelationBody()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_RelationBody();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Association <em>Association</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Association</em>'.
   * @see org.xtext.uma.usex.usex.Association
   * @generated
   */
  EClass getAssociation();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.Composition <em>Composition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Composition</em>'.
   * @see org.xtext.uma.usex.usex.Composition
   * @generated
   */
  EClass getComposition();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.RelationBody <em>Relation Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation Body</em>'.
   * @see org.xtext.uma.usex.usex.RelationBody
   * @generated
   */
  EClass getRelationBody();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.RelationBody#getOriginClass <em>Origin Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Origin Class</em>'.
   * @see org.xtext.uma.usex.usex.RelationBody#getOriginClass()
   * @see #getRelationBody()
   * @generated
   */
  EReference getRelationBody_OriginClass();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.RelationBody#getDestinyClass <em>Destiny Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Destiny Class</em>'.
   * @see org.xtext.uma.usex.usex.RelationBody#getDestinyClass()
   * @see #getRelationBody()
   * @generated
   */
  EReference getRelationBody_DestinyClass();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.RelationMember <em>Relation Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation Member</em>'.
   * @see org.xtext.uma.usex.usex.RelationMember
   * @generated
   */
  EClass getRelationMember();

  /**
   * Returns the meta object for the reference '{@link org.xtext.uma.usex.usex.RelationMember#getClass_ <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Class</em>'.
   * @see org.xtext.uma.usex.usex.RelationMember#getClass_()
   * @see #getRelationMember()
   * @generated
   */
  EReference getRelationMember_Class();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.RelationMember#getCardinality <em>Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cardinality</em>'.
   * @see org.xtext.uma.usex.usex.RelationMember#getCardinality()
   * @see #getRelationMember()
   * @generated
   */
  EReference getRelationMember_Cardinality();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.RelationMember#getRoleName <em>Role Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role Name</em>'.
   * @see org.xtext.uma.usex.usex.RelationMember#getRoleName()
   * @see #getRelationMember()
   * @generated
   */
  EAttribute getRelationMember_RoleName();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.CardinalityType <em>Cardinality Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cardinality Type</em>'.
   * @see org.xtext.uma.usex.usex.CardinalityType
   * @generated
   */
  EClass getCardinalityType();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.SimpleCardinality <em>Simple Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Cardinality</em>'.
   * @see org.xtext.uma.usex.usex.SimpleCardinality
   * @generated
   */
  EClass getSimpleCardinality();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.SimpleCardinality#getCardinality <em>Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cardinality</em>'.
   * @see org.xtext.uma.usex.usex.SimpleCardinality#getCardinality()
   * @see #getSimpleCardinality()
   * @generated
   */
  EReference getSimpleCardinality_Cardinality();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.DoubleCardinality <em>Double Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Double Cardinality</em>'.
   * @see org.xtext.uma.usex.usex.DoubleCardinality
   * @generated
   */
  EClass getDoubleCardinality();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.DoubleCardinality#getOriginCardinality <em>Origin Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Origin Cardinality</em>'.
   * @see org.xtext.uma.usex.usex.DoubleCardinality#getOriginCardinality()
   * @see #getDoubleCardinality()
   * @generated
   */
  EReference getDoubleCardinality_OriginCardinality();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.uma.usex.usex.DoubleCardinality#getDestinyCardinality <em>Destiny Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Destiny Cardinality</em>'.
   * @see org.xtext.uma.usex.usex.DoubleCardinality#getDestinyCardinality()
   * @see #getDoubleCardinality()
   * @generated
   */
  EReference getDoubleCardinality_DestinyCardinality();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.CardinalityValue <em>Cardinality Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cardinality Value</em>'.
   * @see org.xtext.uma.usex.usex.CardinalityValue
   * @generated
   */
  EClass getCardinalityValue();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.IntCardinality <em>Int Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Cardinality</em>'.
   * @see org.xtext.uma.usex.usex.IntCardinality
   * @generated
   */
  EClass getIntCardinality();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.IntCardinality#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.uma.usex.usex.IntCardinality#getValue()
   * @see #getIntCardinality()
   * @generated
   */
  EAttribute getIntCardinality_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.uma.usex.usex.AsteriskCardinality <em>Asterisk Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asterisk Cardinality</em>'.
   * @see org.xtext.uma.usex.usex.AsteriskCardinality
   * @generated
   */
  EClass getAsteriskCardinality();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.uma.usex.usex.AsteriskCardinality#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.uma.usex.usex.AsteriskCardinality#getValue()
   * @see #getAsteriskCardinality()
   * @generated
   */
  EAttribute getAsteriskCardinality_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UsexFactory getUsexFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.ModelImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.AbstractElementImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_ELEMENT__NAME = eINSTANCE.getAbstractElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.UseClassImpl <em>Use Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.UseClassImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getUseClass()
     * @generated
     */
    EClass USE_CLASS = eINSTANCE.getUseClass();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CLASS__ATTRIBUTES = eINSTANCE.getUseClass_Attributes();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CLASS__OPERATIONS = eINSTANCE.getUseClass_Operations();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CLASS__CONSTRAINTS = eINSTANCE.getUseClass_Constraints();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.AttributeImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '<em><b>Initialization</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__INITIALIZATION = eINSTANCE.getAttribute_Initialization();

    /**
     * The meta object literal for the '<em><b>Derived From</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__DERIVED_FROM = eINSTANCE.getAttribute_DerivedFrom();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.AttributeTypeImpl <em>Attribute Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.AttributeTypeImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAttributeType()
     * @generated
     */
    EClass ATTRIBUTE_TYPE = eINSTANCE.getAttributeType();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.PrimitiveTypeImpl <em>Primitive Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.PrimitiveTypeImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getPrimitiveType()
     * @generated
     */
    EClass PRIMITIVE_TYPE = eINSTANCE.getPrimitiveType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIMITIVE_TYPE__TYPE = eINSTANCE.getPrimitiveType_Type();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.ClassTypeImpl <em>Class Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.ClassTypeImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getClassType()
     * @generated
     */
    EClass CLASS_TYPE = eINSTANCE.getClassType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_TYPE__TYPE = eINSTANCE.getClassType_Type();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.AttributeInitializationImpl <em>Attribute Initialization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.AttributeInitializationImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAttributeInitialization()
     * @generated
     */
    EClass ATTRIBUTE_INITIALIZATION = eINSTANCE.getAttributeInitialization();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.DoubleInitializationImpl <em>Double Initialization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.DoubleInitializationImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getDoubleInitialization()
     * @generated
     */
    EClass DOUBLE_INITIALIZATION = eINSTANCE.getDoubleInitialization();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOUBLE_INITIALIZATION__VALUE = eINSTANCE.getDoubleInitialization_Value();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.BooleanInitializationImpl <em>Boolean Initialization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.BooleanInitializationImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getBooleanInitialization()
     * @generated
     */
    EClass BOOLEAN_INITIALIZATION = eINSTANCE.getBooleanInitialization();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_INITIALIZATION__VALUE = eINSTANCE.getBooleanInitialization_Value();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.IntegerInitializationImpl <em>Integer Initialization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.IntegerInitializationImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getIntegerInitialization()
     * @generated
     */
    EClass INTEGER_INITIALIZATION = eINSTANCE.getIntegerInitialization();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTEGER_INITIALIZATION__VALUE = eINSTANCE.getIntegerInitialization_Value();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.StringInitializationImpl <em>String Initialization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.StringInitializationImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getStringInitialization()
     * @generated
     */
    EClass STRING_INITIALIZATION = eINSTANCE.getStringInitialization();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_INITIALIZATION__VALUE = eINSTANCE.getStringInitialization_Value();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.OperationImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__NAME = eINSTANCE.getOperation_Name();

    /**
     * The meta object literal for the '<em><b>Input Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__INPUT_PARAMETERS = eINSTANCE.getOperation_InputParameters();

    /**
     * The meta object literal for the '<em><b>Return Parameter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__RETURN_PARAMETER = eINSTANCE.getOperation_ReturnParameter();

    /**
     * The meta object literal for the '<em><b>Operation Body</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__OPERATION_BODY = eINSTANCE.getOperation_OperationBody();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.MethodImpl <em>Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.MethodImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getMethod()
     * @generated
     */
    EClass METHOD = eINSTANCE.getMethod();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD__CONDITIONS = eINSTANCE.getMethod_Conditions();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.QueryImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.ParameterImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__TYPE = eINSTANCE.getParameter_Type();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.ConditionImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Condition Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__CONDITION_BODY = eINSTANCE.getCondition_ConditionBody();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.PreconditionImpl <em>Precondition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.PreconditionImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getPrecondition()
     * @generated
     */
    EClass PRECONDITION = eINSTANCE.getPrecondition();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.PostconditionImpl <em>Postcondition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.PostconditionImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getPostcondition()
     * @generated
     */
    EClass POSTCONDITION = eINSTANCE.getPostcondition();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.ConditionBodyImpl <em>Condition Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.ConditionBodyImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getConditionBody()
     * @generated
     */
    EClass CONDITION_BODY = eINSTANCE.getConditionBody();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION_BODY__NAME = eINSTANCE.getConditionBody_Name();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION_BODY__CONDITION = eINSTANCE.getConditionBody_Condition();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.ConstraintImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '<em><b>Condition Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__CONDITION_BODY = eINSTANCE.getConstraint_ConditionBody();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.RelationImpl <em>Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.RelationImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getRelation()
     * @generated
     */
    EClass RELATION = eINSTANCE.getRelation();

    /**
     * The meta object literal for the '<em><b>Relation Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__RELATION_BODY = eINSTANCE.getRelation_RelationBody();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.AssociationImpl <em>Association</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.AssociationImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAssociation()
     * @generated
     */
    EClass ASSOCIATION = eINSTANCE.getAssociation();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.CompositionImpl <em>Composition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.CompositionImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getComposition()
     * @generated
     */
    EClass COMPOSITION = eINSTANCE.getComposition();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.RelationBodyImpl <em>Relation Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.RelationBodyImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getRelationBody()
     * @generated
     */
    EClass RELATION_BODY = eINSTANCE.getRelationBody();

    /**
     * The meta object literal for the '<em><b>Origin Class</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_BODY__ORIGIN_CLASS = eINSTANCE.getRelationBody_OriginClass();

    /**
     * The meta object literal for the '<em><b>Destiny Class</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_BODY__DESTINY_CLASS = eINSTANCE.getRelationBody_DestinyClass();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.RelationMemberImpl <em>Relation Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.RelationMemberImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getRelationMember()
     * @generated
     */
    EClass RELATION_MEMBER = eINSTANCE.getRelationMember();

    /**
     * The meta object literal for the '<em><b>Class</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_MEMBER__CLASS = eINSTANCE.getRelationMember_Class();

    /**
     * The meta object literal for the '<em><b>Cardinality</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_MEMBER__CARDINALITY = eINSTANCE.getRelationMember_Cardinality();

    /**
     * The meta object literal for the '<em><b>Role Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATION_MEMBER__ROLE_NAME = eINSTANCE.getRelationMember_RoleName();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.CardinalityTypeImpl <em>Cardinality Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.CardinalityTypeImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getCardinalityType()
     * @generated
     */
    EClass CARDINALITY_TYPE = eINSTANCE.getCardinalityType();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.SimpleCardinalityImpl <em>Simple Cardinality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.SimpleCardinalityImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getSimpleCardinality()
     * @generated
     */
    EClass SIMPLE_CARDINALITY = eINSTANCE.getSimpleCardinality();

    /**
     * The meta object literal for the '<em><b>Cardinality</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_CARDINALITY__CARDINALITY = eINSTANCE.getSimpleCardinality_Cardinality();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.DoubleCardinalityImpl <em>Double Cardinality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.DoubleCardinalityImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getDoubleCardinality()
     * @generated
     */
    EClass DOUBLE_CARDINALITY = eINSTANCE.getDoubleCardinality();

    /**
     * The meta object literal for the '<em><b>Origin Cardinality</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOUBLE_CARDINALITY__ORIGIN_CARDINALITY = eINSTANCE.getDoubleCardinality_OriginCardinality();

    /**
     * The meta object literal for the '<em><b>Destiny Cardinality</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOUBLE_CARDINALITY__DESTINY_CARDINALITY = eINSTANCE.getDoubleCardinality_DestinyCardinality();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.CardinalityValueImpl <em>Cardinality Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.CardinalityValueImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getCardinalityValue()
     * @generated
     */
    EClass CARDINALITY_VALUE = eINSTANCE.getCardinalityValue();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.IntCardinalityImpl <em>Int Cardinality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.IntCardinalityImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getIntCardinality()
     * @generated
     */
    EClass INT_CARDINALITY = eINSTANCE.getIntCardinality();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_CARDINALITY__VALUE = eINSTANCE.getIntCardinality_Value();

    /**
     * The meta object literal for the '{@link org.xtext.uma.usex.usex.impl.AsteriskCardinalityImpl <em>Asterisk Cardinality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.uma.usex.usex.impl.AsteriskCardinalityImpl
     * @see org.xtext.uma.usex.usex.impl.UsexPackageImpl#getAsteriskCardinality()
     * @generated
     */
    EClass ASTERISK_CARDINALITY = eINSTANCE.getAsteriskCardinality();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASTERISK_CARDINALITY__VALUE = eINSTANCE.getAsteriskCardinality_Value();

  }

} //UsexPackage
