/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.uma.usex.usex.UsexPackage
 * @generated
 */
public interface UsexFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UsexFactory eINSTANCE = org.xtext.uma.usex.usex.impl.UsexFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Abstract Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Element</em>'.
   * @generated
   */
  AbstractElement createAbstractElement();

  /**
   * Returns a new object of class '<em>Use Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Use Class</em>'.
   * @generated
   */
  UseClass createUseClass();

  /**
   * Returns a new object of class '<em>Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute</em>'.
   * @generated
   */
  Attribute createAttribute();

  /**
   * Returns a new object of class '<em>Attribute Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Type</em>'.
   * @generated
   */
  AttributeType createAttributeType();

  /**
   * Returns a new object of class '<em>Primitive Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Type</em>'.
   * @generated
   */
  PrimitiveType createPrimitiveType();

  /**
   * Returns a new object of class '<em>Class Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Type</em>'.
   * @generated
   */
  ClassType createClassType();

  /**
   * Returns a new object of class '<em>Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation</em>'.
   * @generated
   */
  Operation createOperation();

  /**
   * Returns a new object of class '<em>Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method</em>'.
   * @generated
   */
  Method createMethod();

  /**
   * Returns a new object of class '<em>Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query</em>'.
   * @generated
   */
  Query createQuery();

  /**
   * Returns a new object of class '<em>Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter</em>'.
   * @generated
   */
  Parameter createParameter();

  /**
   * Returns a new object of class '<em>Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition</em>'.
   * @generated
   */
  Condition createCondition();

  /**
   * Returns a new object of class '<em>Precondition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Precondition</em>'.
   * @generated
   */
  Precondition createPrecondition();

  /**
   * Returns a new object of class '<em>Postcondition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Postcondition</em>'.
   * @generated
   */
  Postcondition createPostcondition();

  /**
   * Returns a new object of class '<em>Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint</em>'.
   * @generated
   */
  Constraint createConstraint();

  /**
   * Returns a new object of class '<em>Relation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Relation</em>'.
   * @generated
   */
  Relation createRelation();

  /**
   * Returns a new object of class '<em>Relation Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Relation Body</em>'.
   * @generated
   */
  RelationBody createRelationBody();

  /**
   * Returns a new object of class '<em>Relation Member</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Relation Member</em>'.
   * @generated
   */
  RelationMember createRelationMember();

  /**
   * Returns a new object of class '<em>Primitive Type Ref CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Type Ref CS</em>'.
   * @generated
   */
  PrimitiveTypeRefCS createPrimitiveTypeRefCS();

  /**
   * Returns a new object of class '<em>Collection Type CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Collection Type CS</em>'.
   * @generated
   */
  CollectionTypeCS createCollectionTypeCS();

  /**
   * Returns a new object of class '<em>Map Type CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Type CS</em>'.
   * @generated
   */
  MapTypeCS createMapTypeCS();

  /**
   * Returns a new object of class '<em>Tuple Type CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tuple Type CS</em>'.
   * @generated
   */
  TupleTypeCS createTupleTypeCS();

  /**
   * Returns a new object of class '<em>Tuple Part CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tuple Part CS</em>'.
   * @generated
   */
  TuplePartCS createTuplePartCS();

  /**
   * Returns a new object of class '<em>Collection Pattern CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Collection Pattern CS</em>'.
   * @generated
   */
  CollectionPatternCS createCollectionPatternCS();

  /**
   * Returns a new object of class '<em>Pattern Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pattern Exp CS</em>'.
   * @generated
   */
  PatternExpCS createPatternExpCS();

  /**
   * Returns a new object of class '<em>Typed Ref CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Typed Ref CS</em>'.
   * @generated
   */
  TypedRefCS createTypedRefCS();

  /**
   * Returns a new object of class '<em>Type Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Literal Exp CS</em>'.
   * @generated
   */
  TypeLiteralExpCS createTypeLiteralExpCS();

  /**
   * Returns a new object of class '<em>Type Name Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Name Exp CS</em>'.
   * @generated
   */
  TypeNameExpCS createTypeNameExpCS();

  /**
   * Returns a new object of class '<em>Curly Bracketed Clause CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Curly Bracketed Clause CS</em>'.
   * @generated
   */
  CurlyBracketedClauseCS createCurlyBracketedClauseCS();

  /**
   * Returns a new object of class '<em>Shadow Part CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Shadow Part CS</em>'.
   * @generated
   */
  ShadowPartCS createShadowPartCS();

  /**
   * Returns a new object of class '<em>String Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Literal Exp CS</em>'.
   * @generated
   */
  StringLiteralExpCS createStringLiteralExpCS();

  /**
   * Returns a new object of class '<em>Multiplicity Bounds CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multiplicity Bounds CS</em>'.
   * @generated
   */
  MultiplicityBoundsCS createMultiplicityBoundsCS();

  /**
   * Returns a new object of class '<em>Multiplicity CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multiplicity CS</em>'.
   * @generated
   */
  MultiplicityCS createMultiplicityCS();

  /**
   * Returns a new object of class '<em>Multiplicity String CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multiplicity String CS</em>'.
   * @generated
   */
  MultiplicityStringCS createMultiplicityStringCS();

  /**
   * Returns a new object of class '<em>Path Name CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Path Name CS</em>'.
   * @generated
   */
  PathNameCS createPathNameCS();

  /**
   * Returns a new object of class '<em>Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exp CS</em>'.
   * @generated
   */
  ExpCS createExpCS();

  /**
   * Returns a new object of class '<em>Primitive Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Literal Exp CS</em>'.
   * @generated
   */
  PrimitiveLiteralExpCS createPrimitiveLiteralExpCS();

  /**
   * Returns a new object of class '<em>Name Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Name Exp CS</em>'.
   * @generated
   */
  NameExpCS createNameExpCS();

  /**
   * Returns a new object of class '<em>Square Bracketed Clause CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Square Bracketed Clause CS</em>'.
   * @generated
   */
  SquareBracketedClauseCS createSquareBracketedClauseCS();

  /**
   * Returns a new object of class '<em>Collection Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Collection Literal Exp CS</em>'.
   * @generated
   */
  CollectionLiteralExpCS createCollectionLiteralExpCS();

  /**
   * Returns a new object of class '<em>Collection Literal Part CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Collection Literal Part CS</em>'.
   * @generated
   */
  CollectionLiteralPartCS createCollectionLiteralPartCS();

  /**
   * Returns a new object of class '<em>Lambda Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lambda Literal Exp CS</em>'.
   * @generated
   */
  LambdaLiteralExpCS createLambdaLiteralExpCS();

  /**
   * Returns a new object of class '<em>Map Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Literal Exp CS</em>'.
   * @generated
   */
  MapLiteralExpCS createMapLiteralExpCS();

  /**
   * Returns a new object of class '<em>Map Literal Part CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Literal Part CS</em>'.
   * @generated
   */
  MapLiteralPartCS createMapLiteralPartCS();

  /**
   * Returns a new object of class '<em>Tuple Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tuple Literal Exp CS</em>'.
   * @generated
   */
  TupleLiteralExpCS createTupleLiteralExpCS();

  /**
   * Returns a new object of class '<em>Tuple Literal Part CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tuple Literal Part CS</em>'.
   * @generated
   */
  TupleLiteralPartCS createTupleLiteralPartCS();

  /**
   * Returns a new object of class '<em>Number Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Number Literal Exp CS</em>'.
   * @generated
   */
  NumberLiteralExpCS createNumberLiteralExpCS();

  /**
   * Returns a new object of class '<em>Boolean Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Literal Exp CS</em>'.
   * @generated
   */
  BooleanLiteralExpCS createBooleanLiteralExpCS();

  /**
   * Returns a new object of class '<em>Unlimited Natural Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unlimited Natural Literal Exp CS</em>'.
   * @generated
   */
  UnlimitedNaturalLiteralExpCS createUnlimitedNaturalLiteralExpCS();

  /**
   * Returns a new object of class '<em>Invalid Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invalid Literal Exp CS</em>'.
   * @generated
   */
  InvalidLiteralExpCS createInvalidLiteralExpCS();

  /**
   * Returns a new object of class '<em>Null Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Null Literal Exp CS</em>'.
   * @generated
   */
  NullLiteralExpCS createNullLiteralExpCS();

  /**
   * Returns a new object of class '<em>Nested Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nested Exp CS</em>'.
   * @generated
   */
  NestedExpCS createNestedExpCS();

  /**
   * Returns a new object of class '<em>If Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>If Exp CS</em>'.
   * @generated
   */
  IfExpCS createIfExpCS();

  /**
   * Returns a new object of class '<em>If Then Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>If Then Exp CS</em>'.
   * @generated
   */
  IfThenExpCS createIfThenExpCS();

  /**
   * Returns a new object of class '<em>Let Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Let Exp CS</em>'.
   * @generated
   */
  LetExpCS createLetExpCS();

  /**
   * Returns a new object of class '<em>Let Variable CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Let Variable CS</em>'.
   * @generated
   */
  LetVariableCS createLetVariableCS();

  /**
   * Returns a new object of class '<em>Round Bracketed Clause CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Round Bracketed Clause CS</em>'.
   * @generated
   */
  RoundBracketedClauseCS createRoundBracketedClauseCS();

  /**
   * Returns a new object of class '<em>Navigating Arg CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Navigating Arg CS</em>'.
   * @generated
   */
  NavigatingArgCS createNavigatingArgCS();

  /**
   * Returns a new object of class '<em>Variable CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable CS</em>'.
   * @generated
   */
  VariableCS createVariableCS();

  /**
   * Returns a new object of class '<em>Infix Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Infix Exp CS</em>'.
   * @generated
   */
  InfixExpCS createInfixExpCS();

  /**
   * Returns a new object of class '<em>Prefix Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Prefix Exp CS</em>'.
   * @generated
   */
  PrefixExpCS createPrefixExpCS();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  UsexPackage getUsexPackage();

} //UsexFactory
