/*
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.uma.usex.ui.internal.UsexActivator;

public class UsexUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UsexActivator.getInstance().getInjector("org.xtext.uma.usex.Usex");
	}

}
