/*
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUsexScopeProvider extends DelegatingScopeProvider {
}
