/*
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.uma.usex.UsexRuntimeModule;
import org.xtext.uma.usex.UsexStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UsexIdeSetup extends UsexStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UsexRuntimeModule(), new UsexIdeModule()));
	}
	
}
