/*
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UsexStandaloneSetup extends UsexStandaloneSetupGenerated {

	public static void doSetup() {
		new UsexStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
