/*
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UsexAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/uma/usex/parser/antlr/internal/InternalUsex.tokens");
	}
}
