/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.uma.usex.usex.CardinalityValue;
import org.xtext.uma.usex.usex.DoubleCardinality;
import org.xtext.uma.usex.usex.UsexPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Double Cardinality</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.uma.usex.usex.impl.DoubleCardinalityImpl#getOriginCardinality <em>Origin Cardinality</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.impl.DoubleCardinalityImpl#getDestinyCardinality <em>Destiny Cardinality</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DoubleCardinalityImpl extends CardinalityTypeImpl implements DoubleCardinality
{
  /**
   * The cached value of the '{@link #getOriginCardinality() <em>Origin Cardinality</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOriginCardinality()
   * @generated
   * @ordered
   */
  protected CardinalityValue originCardinality;

  /**
   * The cached value of the '{@link #getDestinyCardinality() <em>Destiny Cardinality</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDestinyCardinality()
   * @generated
   * @ordered
   */
  protected CardinalityValue destinyCardinality;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DoubleCardinalityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UsexPackage.Literals.DOUBLE_CARDINALITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CardinalityValue getOriginCardinality()
  {
    return originCardinality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOriginCardinality(CardinalityValue newOriginCardinality, NotificationChain msgs)
  {
    CardinalityValue oldOriginCardinality = originCardinality;
    originCardinality = newOriginCardinality;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UsexPackage.DOUBLE_CARDINALITY__ORIGIN_CARDINALITY, oldOriginCardinality, newOriginCardinality);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOriginCardinality(CardinalityValue newOriginCardinality)
  {
    if (newOriginCardinality != originCardinality)
    {
      NotificationChain msgs = null;
      if (originCardinality != null)
        msgs = ((InternalEObject)originCardinality).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UsexPackage.DOUBLE_CARDINALITY__ORIGIN_CARDINALITY, null, msgs);
      if (newOriginCardinality != null)
        msgs = ((InternalEObject)newOriginCardinality).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UsexPackage.DOUBLE_CARDINALITY__ORIGIN_CARDINALITY, null, msgs);
      msgs = basicSetOriginCardinality(newOriginCardinality, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsexPackage.DOUBLE_CARDINALITY__ORIGIN_CARDINALITY, newOriginCardinality, newOriginCardinality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CardinalityValue getDestinyCardinality()
  {
    return destinyCardinality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDestinyCardinality(CardinalityValue newDestinyCardinality, NotificationChain msgs)
  {
    CardinalityValue oldDestinyCardinality = destinyCardinality;
    destinyCardinality = newDestinyCardinality;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UsexPackage.DOUBLE_CARDINALITY__DESTINY_CARDINALITY, oldDestinyCardinality, newDestinyCardinality);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDestinyCardinality(CardinalityValue newDestinyCardinality)
  {
    if (newDestinyCardinality != destinyCardinality)
    {
      NotificationChain msgs = null;
      if (destinyCardinality != null)
        msgs = ((InternalEObject)destinyCardinality).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UsexPackage.DOUBLE_CARDINALITY__DESTINY_CARDINALITY, null, msgs);
      if (newDestinyCardinality != null)
        msgs = ((InternalEObject)newDestinyCardinality).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UsexPackage.DOUBLE_CARDINALITY__DESTINY_CARDINALITY, null, msgs);
      msgs = basicSetDestinyCardinality(newDestinyCardinality, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsexPackage.DOUBLE_CARDINALITY__DESTINY_CARDINALITY, newDestinyCardinality, newDestinyCardinality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UsexPackage.DOUBLE_CARDINALITY__ORIGIN_CARDINALITY:
        return basicSetOriginCardinality(null, msgs);
      case UsexPackage.DOUBLE_CARDINALITY__DESTINY_CARDINALITY:
        return basicSetDestinyCardinality(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UsexPackage.DOUBLE_CARDINALITY__ORIGIN_CARDINALITY:
        return getOriginCardinality();
      case UsexPackage.DOUBLE_CARDINALITY__DESTINY_CARDINALITY:
        return getDestinyCardinality();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UsexPackage.DOUBLE_CARDINALITY__ORIGIN_CARDINALITY:
        setOriginCardinality((CardinalityValue)newValue);
        return;
      case UsexPackage.DOUBLE_CARDINALITY__DESTINY_CARDINALITY:
        setDestinyCardinality((CardinalityValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UsexPackage.DOUBLE_CARDINALITY__ORIGIN_CARDINALITY:
        setOriginCardinality((CardinalityValue)null);
        return;
      case UsexPackage.DOUBLE_CARDINALITY__DESTINY_CARDINALITY:
        setDestinyCardinality((CardinalityValue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UsexPackage.DOUBLE_CARDINALITY__ORIGIN_CARDINALITY:
        return originCardinality != null;
      case UsexPackage.DOUBLE_CARDINALITY__DESTINY_CARDINALITY:
        return destinyCardinality != null;
    }
    return super.eIsSet(featureID);
  }

} //DoubleCardinalityImpl
