/**
 * generated by Xtext 2.25.0
 */
package org.xtext.uma.usex.usex.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.uma.usex.usex.AttributeType;
import org.xtext.uma.usex.usex.ExpCS;
import org.xtext.uma.usex.usex.Operation;
import org.xtext.uma.usex.usex.Parameter;
import org.xtext.uma.usex.usex.UsexPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.uma.usex.usex.impl.OperationImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.impl.OperationImpl#getInputParameters <em>Input Parameters</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.impl.OperationImpl#getReturnParameter <em>Return Parameter</em>}</li>
 *   <li>{@link org.xtext.uma.usex.usex.impl.OperationImpl#getOperationBody <em>Operation Body</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OperationImpl extends MinimalEObjectImpl.Container implements Operation
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getInputParameters() <em>Input Parameters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputParameters()
   * @generated
   * @ordered
   */
  protected EList<Parameter> inputParameters;

  /**
   * The cached value of the '{@link #getReturnParameter() <em>Return Parameter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReturnParameter()
   * @generated
   * @ordered
   */
  protected AttributeType returnParameter;

  /**
   * The cached value of the '{@link #getOperationBody() <em>Operation Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperationBody()
   * @generated
   * @ordered
   */
  protected ExpCS operationBody;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UsexPackage.Literals.OPERATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsexPackage.OPERATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Parameter> getInputParameters()
  {
    if (inputParameters == null)
    {
      inputParameters = new EObjectContainmentEList<Parameter>(Parameter.class, this, UsexPackage.OPERATION__INPUT_PARAMETERS);
    }
    return inputParameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AttributeType getReturnParameter()
  {
    return returnParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReturnParameter(AttributeType newReturnParameter, NotificationChain msgs)
  {
    AttributeType oldReturnParameter = returnParameter;
    returnParameter = newReturnParameter;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UsexPackage.OPERATION__RETURN_PARAMETER, oldReturnParameter, newReturnParameter);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReturnParameter(AttributeType newReturnParameter)
  {
    if (newReturnParameter != returnParameter)
    {
      NotificationChain msgs = null;
      if (returnParameter != null)
        msgs = ((InternalEObject)returnParameter).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UsexPackage.OPERATION__RETURN_PARAMETER, null, msgs);
      if (newReturnParameter != null)
        msgs = ((InternalEObject)newReturnParameter).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UsexPackage.OPERATION__RETURN_PARAMETER, null, msgs);
      msgs = basicSetReturnParameter(newReturnParameter, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsexPackage.OPERATION__RETURN_PARAMETER, newReturnParameter, newReturnParameter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpCS getOperationBody()
  {
    return operationBody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOperationBody(ExpCS newOperationBody, NotificationChain msgs)
  {
    ExpCS oldOperationBody = operationBody;
    operationBody = newOperationBody;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UsexPackage.OPERATION__OPERATION_BODY, oldOperationBody, newOperationBody);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperationBody(ExpCS newOperationBody)
  {
    if (newOperationBody != operationBody)
    {
      NotificationChain msgs = null;
      if (operationBody != null)
        msgs = ((InternalEObject)operationBody).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UsexPackage.OPERATION__OPERATION_BODY, null, msgs);
      if (newOperationBody != null)
        msgs = ((InternalEObject)newOperationBody).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UsexPackage.OPERATION__OPERATION_BODY, null, msgs);
      msgs = basicSetOperationBody(newOperationBody, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsexPackage.OPERATION__OPERATION_BODY, newOperationBody, newOperationBody));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UsexPackage.OPERATION__INPUT_PARAMETERS:
        return ((InternalEList<?>)getInputParameters()).basicRemove(otherEnd, msgs);
      case UsexPackage.OPERATION__RETURN_PARAMETER:
        return basicSetReturnParameter(null, msgs);
      case UsexPackage.OPERATION__OPERATION_BODY:
        return basicSetOperationBody(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UsexPackage.OPERATION__NAME:
        return getName();
      case UsexPackage.OPERATION__INPUT_PARAMETERS:
        return getInputParameters();
      case UsexPackage.OPERATION__RETURN_PARAMETER:
        return getReturnParameter();
      case UsexPackage.OPERATION__OPERATION_BODY:
        return getOperationBody();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UsexPackage.OPERATION__NAME:
        setName((String)newValue);
        return;
      case UsexPackage.OPERATION__INPUT_PARAMETERS:
        getInputParameters().clear();
        getInputParameters().addAll((Collection<? extends Parameter>)newValue);
        return;
      case UsexPackage.OPERATION__RETURN_PARAMETER:
        setReturnParameter((AttributeType)newValue);
        return;
      case UsexPackage.OPERATION__OPERATION_BODY:
        setOperationBody((ExpCS)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UsexPackage.OPERATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case UsexPackage.OPERATION__INPUT_PARAMETERS:
        getInputParameters().clear();
        return;
      case UsexPackage.OPERATION__RETURN_PARAMETER:
        setReturnParameter((AttributeType)null);
        return;
      case UsexPackage.OPERATION__OPERATION_BODY:
        setOperationBody((ExpCS)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UsexPackage.OPERATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case UsexPackage.OPERATION__INPUT_PARAMETERS:
        return inputParameters != null && !inputParameters.isEmpty();
      case UsexPackage.OPERATION__RETURN_PARAMETER:
        return returnParameter != null;
      case UsexPackage.OPERATION__OPERATION_BODY:
        return operationBody != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //OperationImpl
